baseURL = '/'
languageCode = 'en-us'
title = 'Hugo content filters'

[taxonomies]
    category = 'categories'
    tag = 'tags'

[pagination]
    disableAliases = true
    pagerSize = 5

[caches]
    [caches.images]
        dir = ':cacheDir/images'

[markup.goldmark.renderer]
    hardWraps = false
    unsafe = true

[markup.goldmark.parser]
    wrapStandAloneImageWithinParagraph = false
    autoHeadingID = false
